### PR TITLE
rEFInd installation

### PR DESCRIPTION
**Pull request by Randomguy-8**

### CODE REVIEW

**Comment by axonasif** [comment]
@hmtheboy154 can you help me co-review his PR?

**Comment by hmtheboy154** [comment]
- Explain what is rEFInd and noted that it's only for UEFI (the EFI in rEFInd)
- Why there's a `## Getting grub` at the start ? 
- The Linux install part need to edit more, we need to split into 2 part :
+ The package-install : .deb install is not just for Ubuntu, it's for all Debian-based distro as a whole, so noted that
There's also rpm-based distro, if you know how to install *.rpm then you can add them in, keep in mind that we have 1 exception it's Mageia which it already have rEFInd in its repo and you can just `sudo urpmi refind`.
For Arch, just straight up telling people to make install using pacman, don't throw Archwiki yet `sudo pacman -S refind` 
https://archlinux.org/packages/extra/any/refind/

+ The refind-install : When refind is installing it will install a script `refind-install`, after install the package (based on your distro) the package will automatically run the script. 
But, in case there's something wrong or it didn't run, run the script manually again : `sudo refind-install`

**Comment by hmtheboy154** [comment]
- This part I mean that showing people how to install *.deb and *.rpm, not just one command apt like this, download the *.deb or *.rpm based on the distro on rEFInd sourceforge and install since those are their latest version 
image
Finding how to install *.deb and *.rpm and then write them here

But on Ubuntu rEFInd does have a ppa for latest version so Ubuntu users can add this and apt install it 
https://launchpad.net/~rodsmith/+archive/ubuntu/refind

- You just need `refind-install` or `sudo refind-install` , that's all, no need to be complicated like this

image

**Comment by Randomguy-8** [comment]
well arch also has latest rEFInd packge in its repository so i kept it at it is...
and added rpm and deb based installation for other linux

**Review by SGNight — APPROVED** [review]

**Pull request merged**
